-- INSERT INTO event
-- ( eventName, dateOccur, creatorId) 
-- VALUES 
-- ('Moab Trip', 'Wednesday 08-01-17', 1),
-- ('Dinner at BurgerKing', 'Wednesday 08-01-17', 2),
-- ('Jeremy Birthday', 'Thursday 08-02-17, 3)